DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    name  VARCHAR(255) NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT         NOT NULL,
    requestor_id BIGINT       NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_requests PRIMARY KEY (id),

    CONSTRAINT fk_requests_requestor
        FOREIGN KEY (requestor_id) REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_requests_requestor
    ON requests (requestor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    available   BOOLEAN      NOT NULL DEFAULT TRUE,
    owner       BIGINT       NOT NULL,
    request     BIGINT,

    CONSTRAINT pk_items PRIMARY KEY (id),

    CONSTRAINT fk_items_owner
        FOREIGN KEY (owner) REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_items_request
        FOREIGN KEY (request) REFERENCES requests (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_items_owner
    ON items (owner);

CREATE INDEX IF NOT EXISTS idx_items_request
    ON items (request);

CREATE TABLE IF NOT EXISTS bookings (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    BIGINT      NOT NULL,
    booker_id  BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,

    CONSTRAINT pk_bookings PRIMARY KEY (id),

    CONSTRAINT fk_bookings_item
        FOREIGN KEY (item_id) REFERENCES items (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bookings_booker
        FOREIGN KEY (booker_id) REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_bookings_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_bookings_status
        CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX IF NOT EXISTS idx_bookings_item_time
    ON bookings (item_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_bookings_booker
    ON bookings (booker_id, start_time DESC);

CREATE INDEX IF NOT EXISTS idx_bookings_status
    ON bookings (status);

CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(1000) NOT NULL,
    item_id    BIGINT       NOT NULL,
    author_id  BIGINT       NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_comments PRIMARY KEY (id),

    CONSTRAINT fk_comments_item
        FOREIGN KEY (item_id) REFERENCES items (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_item
    ON comments (item_id, created_at DESC);